CREATE TABLE `tb_board` (
  `BOARD_SEQ` int(11) NOT NULL AUTO_INCREMENT COMMENT '순번',
  `BOARD_RE_REF` int(11) DEFAULT NULL COMMENT '원글번호',
  `BOARD_RE_LEV` int(11) DEFAULT NULL COMMENT '원글레벨',
  `BOARD_RE_SEQ` int(11) DEFAULT NULL COMMENT '원글순번',
  `BOARD_WRITER` varchar(300) DEFAULT NULL COMMENT '글쓴이',
  `BOARD_SUBJECT` varchar(300) DEFAULT NULL COMMENT '글제목',
  `BOARD_CONTENT` text DEFAULT NULL COMMENT '글내용',
  `BOARD_HITS` int(11) DEFAULT NULL COMMENT '조회수',
  `INS_USER_ID` varchar(300) DEFAULT NULL COMMENT '최초입력자',
  `INS_DATE` datetime DEFAULT NULL COMMENT '최초입력시간',
  `UPD_USER_ID` varchar(300) DEFAULT NULL COMMENT '수정자',
  `UPD_DATE` datetime DEFAULT NULL COMMENT '수정시간',
  `DEL_YN` varchar(10) DEFAULT NULL COMMENT '삭제여부',
  `PASSWORD` varchar(300) DEFAULT NULL COMMENT '삭제암호',
  PRIMARY KEY (`BOARD_SEQ`)
)